version: '3.8'

services:

  wordpress:
    image: wordpress:php8.1
    restart: always
    ports:
      ## Access on localhost:8080
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      # - wordpress:/var/www/html
      ## Local access to wordpress files
      - type: bind
        source: ./src
        target: /var/www/html

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
    secrets:
      - MYSQL_ROOT_PASSWORD
    volumes:
      ## Named volume for database, as we'll access it through phpmyadmin
      - db:/var/lib/mysql

## Not stored in the public repo, only get them in local environnement from private repo
## Real file will have all secrets files suffixed by '_secret'
secrets:
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD.txt

volumes:
  wordpress:
  db:
