version: '3.8'

services:

  db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: no
      MYSQL_DATABASE_FILE: /run/secrets/MYSQL_DATABASE
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_USER_FILE: /run/secrets/MYSQL_USER
    healthcheck:
      test: 'stat /var/run/mysqld || exit 1'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
    image: mysql:latest
    restart: always
    secrets:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    volumes:
      ## Named volume for database, as we'll access it through phpmyadmin
      - db:/var/lib/mysql
  
  phpmyadmin:
    healthcheck:
      test: 'stat /var/www/html/index.php || exit 1'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
    image: phpmyadmin:latest
    ports:
      ## Access on localhost:8081, 8080 is already taken by web server
      - 8081:80
    restart: always
  
  wordpress:
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME_FILE: /run/secrets/MYSQL_DATABASE
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      WORDPRESS_DB_USER_FILE: /run/secrets/MYSQL_USER
      # WORDPRESS_DEBUG: 1
      WORDPRESS_TABLE_PREFIX_FILE: /run/secrets/WORDPRESS_TABLE_PREFIX
    healthcheck:
      test: 'stat /var/www/html/index.php || exit 1'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
    image: wordpress:6.0.0-php8.1-apache
    ports:
      ## Access on localhost:8080
      - 8080:80
    restart: always
    secrets:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
      - WORDPRESS_TABLE_PREFIX
    volumes:
      # - wordpress:/var/www/html
      ## Local access to wordpress files
      - source: ./src
        target: /var/www/html
        type: bind

## Not stored in the public repo, only get them in local environnement from private repo
## Real file will have all secrets files suffixed by '_secret'
secrets:
  MYSQL_DATABASE:
    file: ./secrets/MYSQL_DATABASE.txt
  MYSQL_PASSWORD:
    file: ./secrets/MYSQL_PASSWORD.txt
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD.txt
  MYSQL_USER:
    file: ./secrets/MYSQL_USER.txt
  WORDPRESS_TABLE_PREFIX:
    file: ./secrets/WORDPRESS_TABLE_PREFIX.txt

volumes:
  db:
  wordpress:
